#-*-coding:utf8;-*-
#qpy:console

import time
print ()
print ()
print ()
print ()
print ("BEM VINDO A")
print ()
print ()
time.sleep (1)
print ()
print ()
print ("===========================")
print ("        |D.H.C_team|       ")
print ("===========================")
print ()
time.sleep (2)
print ()
print ("CRIADO POR: jose lucas")
print ()
time.sleep (1)
print ()
print ()
print ()
time.sleep (2)
nome = input ('Qual o seu nome?')

print ()
time.sleep (2)

print ('ESSE E O CORNO >>> ',nome,)
print ()
time.sleep (3)
print ()
print ("vamos as ferramentas?")
print ()
print ("===========")
print ("[1]sim")
print ("[2]não")
print ("===========")
time.sleep (5)
print ()
print ()
print ("ESCOLHA O QUE DESEJA USAR!")
time.sleep (2)
print ("======================")
print ()
print ("[1]attack ddos")
print ("[2]sql injection")
print ()
print ("======================")
print ()
time.sleep (8)
print ("===========CAREGANDO=============")
print ("[*]•••                        10%")
time.sleep (2)
print ("[*]•••••••••                  20%")
time.sleep (1)
print ("[*]•••••••••••••••            50%")
time.sleep (2)
print ("[*]••••••••••••••••••••       70%")
time.sleep (3)
print ("[*]••••••••••••••••••••••••• 100%")
print ("=================================")
time.sleep (2)
print ()
print ()
print ("HACKED BY:D.H.C_team")
print ()
print ()
time.sleep (4)
print ("COPIANDO TODOS OS DADOS DO APARELHO!")
print ()
time.sleep (2)
print ("RASTREANDO DISPOSITIVO!")
print ()
time.sleep (3)
print ("EXCLUINDO TODOS OS DADOS DO APARELHO!")
print ()
time.sleep (5)
print ()
print ()
print ()
print ("CALMA KRAI E PEGADINHA")
print ()
print ()
print ()
print ("depois eu fasso um script privado pra vcs so pelo susto que vcs tomaram agr kkkkkkk")
time.sleep (4)
print ()
print ("auto apagando script em 10 segundos")
print ("10")
time.sleep (1)
print ("9")
time.sleep (1)
print ("8")
time.sleep (1)
print ("7")
time.sleep (1)
print ("6")
time.sleep (1)
print ("5")
time.sleep (1)
print ("4")
time.sleep (1)
print ("3")
time.sleep (1)
print ("2")
time.sleep (1)
print ("1")
time.sleep (1)
print ("0")
time.sleep (1)
print ("auto apagando")
time.sleep (2)
quit=exit
exit


